Feature/tuff 48 remove market trend
BuffChain/tufftoken pull request #17
Opened 2022-01-14 00:39 UTC by ianballard

2022-01-14 01:51 UTC, unibeck requested changes

2022-01-14 01:53 UTC, ianballard commented on .gitignore
> +/yarn.lock
not sure how that got in. i didnt add it explicity. prob from intellij

2022-01-14 01:55 UTC, ianballard commented on contracts/v7/UniswapManager.sol
> +        amountOut = ss.swapRouter.exactInputSingle(params);
it is implicitly returned like checkUpkeep() returns (bool needed). the named returns declaration handles it

2022-01-14 01:56 UTC, ianballard commented on deploy/0002_create_uniswap_pool.js
> +const utils = require("../utils/test_utils");
it was a missed removal. it was being used in a previous commit when attempting to mint a position with uniswap's non fungible position manager

2022-01-14 02:02 UTC, ianballard commented on deploy/0002_create_uniswap_pool.js
> +    const price = 0.00000313875
this was intentionally a magic number for now. I think the best way to accomplish this may be with our liquidity pool being  TUFF/USDC or another stable coin so that it can be a constant. there are other benefits of having our pool be a stable coin pair especially when we are needing to swap to said pair(s) when adding to our lending pool positions. I think that is a question for another day though. So until then I will just make this a constant.

2022-01-14 02:03 UTC, ianballard commented on test/unit_tests/tuffKeeper.js
> +        expect(needed).to.equal(false, "should need upkeep.");
these are remnants from old tests that we still need to clean up

2022-01-14 02:03 UTC, ianballard commented on test/unit_tests/tuffKeeper.js
> +        await tuffTokenDiamond.performUpkeep(randomBytes(0));
these are remnants from old tests that we still need to clean up

2022-01-14 03:52 UTC, ianballard commented on deploy/0002_create_uniswap_pool.js
> +    const price = 0.00000313875
moved to consts for now with a todo to discuss approach

2022-01-15 00:58 UTC, unibeck commented on contracts/v7/UniswapManager.sol
> +        amountOut = ss.swapRouter.exactInputSingle(params);
Nice!

2022-01-15 01:06 UTC, unibeck approved these changes

2022-01-15 01:06 UTC, merged